name = "examples"
description = "Examples for gir_reader library"
version = "0.1.0-dev"

authors = ["H. ROMANO"]
maintainers = ["H. ROMANO <shuihuzhuan@free.fr>"]
maintainers-logins = ["HROMANO"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = "https://github.com/HROMANO"
tags = ["gir", "gtk"]

executables = ["examples"]

[[depends-on]]
gir_reader = "*"

[[pins]]
gir_reader = { path='..' }
